# Generated by Django 4.2.7 on 2023-11-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deapp', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
